services:
  caddy:
    image: erfianugrah/caddy-cfdns:v1.3.8-2.8.4
    hostname: caddy
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 1024M
    volumes:
      # - /mnt/user/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/user/data/caddy/site:/srv
      - /mnt/user/data/caddy/data:/data
      - /mnt/user/data/caddy/config:/config
      - /mnt/user/data/caddy/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=0000
      - TZ=Asia/Singapore
      - CF_API_TOKEN=${CF_API_TOKEN}
      - EMAIL=${EMAIL}
